### ISSUE TITLE
maggiore-o-minore.js

### ISSUE THREAD

**Issue by bl0nnn** [AlbertoOlla/esercizi-di-programmazione-javascript#5]
come posso determinare il numero maggiore e minore nell'esercizio (maggiore-o-minore.js) senza una funzione ma solo utilizzando dell condizioni?

**Comment by KimCoder75** [comment]
facendo un'iterazione di confronto tra tutti i numeri a due a due.

sottraendo il secondo al primo.

creando tre scenari possibili

risultato è maggiore di 0
risultato = 0
risultato minore 0

a questo punto posso avere vari scenari

ne prendo due ad esempio

variante 1
se sono semplici numeri
posso utilizzare delle variabili di appoggio per poi restituire l'ordine
desiderato.

variante 2
se sono all'interno di un'array, modifico gli indici con i metodi slice o
splice oppure
con il medodo push aggiungo un elemento in più di appogio che riceverà un
nuovo indice.

e alla fine impongo di tutto, impongo la lunghezza dell'array pari a quella
iniziale tagliando di fatto gli elementi di appoggio che saranno alla fine.

Come ciclo utilizzo while perchè non conosco il numero di iterazioni
necessarie per finire.

Ciao e grazie per l'interrogazione a sorpresa.

Kim Malcaus

Ciao e grazie per l'interrogazione a sorpresa.

Kim Malcaus

Il dom 14 giu 2020, 00:50 Null0049 <notifications@github.com> ha scritto:

**Comment by bl0nnn** [comment]
Potresti farmi un esempio? Non riesco a capire come fare l’iterazione di confronto.. Devo creare delle variabili di appoggio?

**Comment by bl0nnn** [comment]
risolto!!! :)

**Comment by KimCoder75** [comment]
### Maggiore o minore

Ciao Alberto, 
anche se avevo già evidenziato la necessità di una variabile di appoggio, riscrivo il tutto per maggior chiarezza.

Il problema è estremamente lineare da risolvere:

Creo un ciclo facendogli fare un'iterazione di confronto tra tutti i numeri a due a due.

- Posso verificare se il primo elemento sia maggiore del secondo (1). (Segue dettaglio passo a passo)
- Posso sottrarre il secondo numero al primo e lavorare con il risultato (2).

1. Se verifico la condizione che il primo numero sia minore del secondo, avrò semplicemente due risultati: true o false.
2. Se utilizzo la sottrazione mi trovo di fronte a tre possibili scenari:
risultato >i 0, risultato = 0, risultato < 0 ed utilizzerò il risultato per ordinare gli elementi.

In linea generale il problema si può risolvere in svariati modi, ne prendo due ad esempio:

Modo 1 (utilizzo numeri semplici e una variabile di appoggio.)
Posso utilizzare una variabile di appoggio in cui travaserò gli elementi per poi restituire l'ordine desiderato.

Modo 2 (utilizzo un array con metodi slice o splice oppure utilizzo push per aggiungere un nuovo elemento di appoggio.)

  Se ho utilizzato il metodo push,
  alla fine, prima di restituire il valore del risultato, impongo che la lunghezza dell'array sia uguale
  alla lunghezza dell'array originale, eliminando eventuali elementi di appoggio in coda all'array.

  Se ho utilizzato slice o splice questo non è necessario.

Come cicli da utilizzare ne posso scegliere 3:


1. Se non calcolo il numero di operzioni necessarie utilizzerò **while** o **do... while**
2. Se precalcolo il numero di operazioni necessarie calcolando il numero di elementi che stanno al di sopra della diagonale della matrice delle possibilità.
    - Per numeri non contenuti all'interno di un'array utilizzerò **for**
    - Per numeri contenuti all'interno di un array utilizzerò **forEach** 

### Svolgiamo quanto descritto

Scelgo tre variabili che chiamo x1 x2 e x3, la matrice delle possibilità sarà una 3x3 come segue:
Anzichè fare 9 operazioni mi basterà farne 3, quelle al di sopra della diagonale.

```
    | x1 | x2 | x3 |
x1  | -  | x  | x  |
x2  | -  | -  | x  |
x3  | -  | -  | -  |
```
devo confrontare x1 con x2,  x1 con x3 e x2 con x3.

### Svolgimento passo dopo passo.

Creaiamo lo scenario più sconveniente: 

- i numeri sono in ordine crescente: 5, 7, 9
- li voglio ordinare in modo decrescente: 9, 7, 5

Dovrò verificare che le seguenti condizioni risultino vere utilizzando if, else, in questo caso è superfluo:
- x1 < x2
- x1 < x3
- x2 < x3
```
//definisco le variabili.

var x1=5;
var x2=7;
var x3=9;

console.log(`Numeri iniziali: ${x1},${x2},${x3}`);
// Se x1 < x2,  scambia i numeri passando attraverso un variabile di appoggio y

if (x1 < x2) {
y = x2; // copia x2 in y
x2 = x1 // copia x1 in x2
x1 = y // copia y in x1
}

// Se x1 < x3,  scambia i numeri passando attraverso un variabile di appoggio y

if (x1 < x3) {
y = x3; // copia x3 in y
x3 = x1 // copia x1 in x3
x1 = y // copia y in x1
}

// Se x2 < x3,  scambia i numeri passando attraverso un variabile di appoggio y

if (x2 < x3) {
y = x3; // copia x3 in y
x3 = x2 // copia x2 in x3
x2 = y // copia y in x2
}
// altrimenti, lascia tutto com'è (in questo caso è else è superfluo)

console.log(`Numeri finali: ${x1},${x2},${x3}`);
```
Quindi riprendendo in nostro caso numerico:

Situazione iniziale: x1=5, x2=7, x3=9

Prima operazione: (x1 < x2), quindi 5<7

if (x1 < x2) {
y = 7 // copia x2 in y
x2 = 5 // copia x1 in x2
x1 = 7 // copia y in x1
}
Risultato : x1=7, x2=5, x3=9

Seconda operazione: (x1 < x3), quindi 7<9

if (x1 < x3) {
y = 9 // copia x3 in y
x3 = 7 // copia x1 in x3
x1 = 9 // copia y in x1
}
Risultato: x1=9, x2=5, x3=7

Terza ed ultima operazione: (x2 < x3), quindi 5>7

if (x2 < x3) {
y = 7 // copia x3 in y
x3 = 5 // copia x2 in x3
x2 = 7 // copia y in x2
}
Risultato: x1=9, x2=7, x3=5

Situazione iniziale: x1=5, x2=7, x3=9
Situazione finale: x1=9, x2=7, x3=5

Problema risolto.

PS. In questo caso specifico, l'esercizio poteva essere risolto con un solo confronto x1<x3, infatti avendo le variabili iniziali: x1=5, x2=7, x3=9;
imponendo di scambiare i valori se x1>x3 avremmo subito avuto: x1=9, x2=7, x3=5;

Attendo tuo feedback (la prossima volta però leggi bene ciò che scrivo ;) )
Kim

**Comment by KimCoder75** [comment]
Maggiore o minore

Ciao Alberto,
anche se avevo già evidenziato la necessità di una variabile di appoggio,
riscrivo il tutto per maggior chiarezza.

Il problema è estremamente lineare da risolvere:

Creo un ciclo facendogli fare un'iterazione di confronto tra tutti i numeri
a due a due.

   - Posso verificare se il primo elemento sia maggiore del secondo (1).
   (Segue dettaglio passo a passo)
   - Posso sottrarre il secondo numero al primo e lavorare con il risultato
   (2).


   1. Se verifico la condizione che il primo numero sia minore del secondo,
   avrò semplicemente due risultati: true o false.
   2. Se utilizzo la sottrazione mi trovo di fronte a tre possibili scenari:
   risultato >i 0, risultato = 0, risultato < 0 ed utilizzerò il risultato
   per ordinare gli elementi.

In linea generale il problema si può risolvere in svariati modi, ne prendo
due ad esempio:

Modo 1 (utilizzo numeri semplici e una variabile di appoggio.)
Posso utilizzare una variabile di appoggio in cui travaserò gli elementi
per poi restituire l'ordine desiderato.

Modo 2 (utilizzo un array con metodi slice o splice oppure utilizzo push
per aggiungere un nuovo elemento di appoggio.)

Se ho utilizzato il metodo push,
alla fine, prima di restituire il valore del risultato, impongo che la
lunghezza dell'array sia uguale
alla lunghezza dell'array originale, eliminando eventuali elementi di
appoggio in coda all'array.

Se ho utilizzato slice o splice questo non è necessario.

Come cicli da utilizzare ne posso scegliere 3:

   1. Se non calcolo il numero di operzioni necessarie utilizzerò while o do...
   while
   2. Se precalcolo il numero di operazioni necessarie calcolando il numero
   di elementi che stanno al di sopra della diagonale della matrice delle
   possibilità.
      - Per numeri non contenuti all'interno di un'array utilizzerò for
      - Per numeri contenuti all'interno di un array utilizzerò forEach

Svolgiamo quanto descritto

Scelgo tre variabili che chiamo x1 x2 e x3, la matrice delle possibilità
sarà una 3x3 come segue:
Anzichè fare 9 operazioni mi basterà farne 3, quelle al di sopra della
diagonale.

    | x1 | x2 | x3 |
x1  | -  | x  | x  |
x2  | -  | -  | x  |
x3  | -  | -  | -  |

devo confrontare x1 con x2, x1 con x3 e x2 con x3.
Svolgimento passo dopo passo.

Creaiamo lo scenario più sconveniente:

   - i numeri sono in ordine crescente: 5, 7, 9
   - li voglio ordinare in modo decrescente: 9, 7, 5

Dovrò verificare che le seguenti condizioni risultino vere utilizzando if,
else, in questo caso è superfluo:

   - x1 < x2
   - x1 < x3
   - x2 < x3

//definisco le variabili.

var x1=5;
var x2=7;
var x3=9;

console.log(`Numeri iniziali: ${x1},${x2},${x3}`);
// Se x1 < x2,  scambia i numeri passando attraverso un variabile di appoggio y

if (x1 < x2) {
y = x2; // copia x2 in y
x2 = x1 // copia x1 in x2
x1 = y // copia y in x1
}

// Se x1 < x3,  scambia i numeri passando attraverso un variabile di appoggio y

if (x1 < x3) {
y = x3; // copia x3 in y
x3 = x1 // copia x1 in x3
x1 = y // copia y in x1
}

// Se x2 < x3,  scambia i numeri passando attraverso un variabile di appoggio y

if (x2 < x3) {
y = x3; // copia x3 in y
x3 = x2 // copia x2 in x3
x2 = y // copia y in x2
}
// altrimenti, lascia tutto com'è (in questo caso è else è superfluo)

console.log(`Numeri finali: ${x1},${x2},${x3}`);

Quindi riprendendo in nostro caso numerico:

Situazione iniziale: x1=5, x2=7, x3=9

Prima operazione: (x1 < x2), quindi 5<7

if (x1 < x2) {
y = 7 // copia x2 in y
x2 = 5 // copia x1 in x2
x1 = 7 // copia y in x1
}
Risultato : x1=7, x2=5, x3=9

Seconda operazione: (x1 < x3), quindi 7<9

if (x1 < x3) {
y = 9 // copia x3 in y
x3 = 7 // copia x1 in x3
x1 = 9 // copia y in x1
}
Risultato: x1=9, x2=5, x3=7

Terza ed ultima operazione: (x2 < x3), quindi 5>7

if (x2 < x3) {
y = 7 // copia x3 in y
x3 = 5 // copia x2 in x3
x2 = 7 // copia y in x2
}
Risultato: x1=9, x2=7, x3=5

Situazione iniziale: x1=5, x2=7, x3=9
Situazione finale: x1=9, x2=7, x3=5

Problema risolto.

PS. In questo caso specifico, l'esercizio poteva essere risolto con un solo
confronto x1<x3, infatti avendo le variabili iniziali: x1=5, x2=7, x3=9;
imponendo di scambiare i valori se x1>x3 avremmo subito avuto: x1=9, x2=7,
x3=5;

Attendo tuo feedback (la prossima volta però leggi bene ciò che scrivo ;) )
Kim

Il giorno lun 22 giu 2020 alle ore 02:14 Null0049 <notifications@github.com>
ha scritto:
